### ISSUE TITLE
Unable to remove components from the FOOT area in the `Find on Page` menu

### ISSUE THREAD

**Issue by byronhulcher** [nymag/clay-kiln#1122]
## Bug
Currently clicking on the `trashcan` icon for any of the components listed in the `Foot` tab of the `Find on Page` menu throws a `ReferenceError: removeProp is not defined` error, and does not remove the component.  

<img width="379" alt="screen shot 2018-02-20 at 1 21 20 pm" src="https://user-images.githubusercontent.com/2479295/36441546-f7a3c66c-1640-11e8-8546-44a7ea4064a3.png">

I discovered this locally but I'm able to reproduce it across both https://www.thecut.com and http://nymag.com/strategist

**Comment by nelsonpecora** [comment]
Hmm! We should investigate. That sounds like a syntax error.
