### ISSUE TITLE
Remove "Clay " from npm component labels

### ISSUE THREAD

**Issue by yoshokatana** [nymag/clay-kiln#243]
In the component labels, we're title-casing the names of the components. Now that we have a bunch of components on npm namespaced with `clay-*` the labels look a little weird.

Is it worth it to keep that "Clay " designation in the label, or is that extraneous? (I think it's extraneous)

**Comment by TakenPilot** [comment]
Pics or examples?

**Comment by yoshokatana** [comment]
Oh right!

![screen shot 2015-10-06 at 4 24 49 pm](https://cloud.githubusercontent.com/assets/447522/10321547/5a437ffc-6c47-11e5-936c-6e7c819cbb6c.png)

**Comment by TakenPilot** [comment]
...  Huh.  I guess we should have considered that.

**Comment by TakenPilot** [comment]
Yeah, we should remove those.

**Comment by cruzanmo** [comment]
We could also use the `_label` property.

**Comment by yoshokatana** [comment]
These are for the whole components, though, not just fields. It's used:

* in the "add component" buttons of a componentList
* in the component selector

**Comment by yoshokatana** [comment]
Ok I'll do this first thing tomorrow morning. :tada:
