### ISSUE TITLE
Use px consistently

### ISSUE THREAD

**Issue by cruzanmo** [nymag/clay-kiln#246]
Currently clay-kiln styles use `rem` in some stylesheets and `px` in others. We should make all styles use `rem` (except for borders).

**Comment by yoshokatana** [comment]
We should make all stylesheets use `px`, since we don't control the base font size on pages using `clay-kiln`

**Comment by cruzanmo** [comment]
Yeah, I was wondering about which stance we should take with that.

If we go with `px`, then the issue is to make it consistent throughout the css.

**Comment by yoshokatana** [comment]
Yup, agreed

**Comment by yoshokatana** [comment]
I'll grab this and do it now
