### ISSUE TITLE
Ideas for smart editing

### ISSUE THREAD

**Issue by nelsonpecora** [nymag/clay-kiln#25]
Things to highlight, maybe?
- weak words
- "he said" / "she said"
- passive voice
- homonyms? (parse context and suggest corrections?)
- cliches
- people, places, concepts, Proper Nouns (for spelling and metadata)

Helpful suggestions
- related articles that might be good to link to
- main concepts, to use in structured formats
- [insert something about twitter and facebook and social media / seo here]
- suggestions to include / automatically generate infographics? (probably impossible, but would be cool)

**Comment by TakenPilot** [comment]
There are services for this, and some of them are free.

**Comment by yoshokatana** [comment]
Yep. This is sort of a catchall for figuring out what we want to do when analyzing text as users are writing.

**Comment by nelsonpecora** [comment]
Structured text isn't a platform concern, though we should make sure our plugin api is robust enough to handle this use case
