### ISSUE TITLE
component selector is broken on components under other components

### ISSUE THREAD

**Issue by yoshokatana** [nymag/clay-kiln#254]
![screen shot 2015-10-15 at 3 46 44 pm](https://cloud.githubusercontent.com/assets/447522/10525673/01b8b0be-7354-11e5-8cb2-16100a0f4088.png)

**Comment by TakenPilot** [comment]
Is this a z-index thing?

I don't know of any way to avoid this, because there's always someone that thinks they're more important in the DOM styles.

**Comment by yoshokatana** [comment]
Yeah, ditto. Since this ticket was created we established some z-index rules in kiln, and now it's just up to components to follow them (or break)
