### ISSUE TITLE
focus transfer on up/down arrows

### ISSUE THREAD

**Issue by yoshokatana** [nymag/clay-kiln#30]
transfer focus between components in a list on up/down arrows, e.g. in paragraphs.

(note: I don't see how this would work with anything besides paragraphs)

**Comment by TakenPilot** [comment]
In windows, this is `tab` and `shift-tab`.  It would be nice to take advantage of that to create external consistency.

Also, if we did this, it would be overriding the default tab / up-down arrow behavior.  Is that right?

**Comment by yoshokatana** [comment]
It would depend on the cursor, I believe. e.g. If you're in a paragraph and your cursor is on the last line (not sure how to figure that out), it would unfocus the current paragraph and focus the next one (if it existed).

Frankly I can't see a good way to implement this that isn't super janky. Closing unless we have a better idea.
