### ISSUE TITLE
new page picker

### ISSUE THREAD

**Issue by yoshokatana** [nymag/clay-kiln#317]
When creating a new page, users should be able to choose what layout they want.

* There should be a list of layouts, and certain users (admins) should be able to add/remove layouts from that list
* Maybe an option to simply clone the current page?

**Comment by TakenPilot** [comment]
Are you imaging this in a dialog?  Or would this be something in the toolbar?

**Comment by yoshokatana** [comment]
It could be either, though I'd prefer the latter. (I think the current "new page" button should really become a pane for adding components AND pages)

**Comment by yoshokatana** [comment]
The first step towards this is a pane with a (hardcoded) list of layouts to choose from. @davidandrewfrey is working on that currently

**Comment by yoshokatana** [comment]
it's done
