### ISSUE TITLE
Ideas for pre-publishing UX

### ISSUE THREAD

**Issue by nelsonpecora** [nymag/clay-kiln#319]
### pre-publishing validation and error messaging
- ability to write custom validation rules that run before publishing (done)
- we need some common rules (based on behaviors like `required`) that run on _every_ component
### social sharing
- can we determine how a post will look on social media?
- should we have the option to post to social media automatically when a page is published?
### url stuff
- should we give an example of what the url might look like?
- should we allow users to edit the url at this point?

**Comment by yoshokatana** [comment]
Maybe social stuff and "exporting" stuff (apple news, AMP, instant articles, etc) should be handled in the same place, right before publishing?

**Comment by TakenPilot** [comment]
> we need some common rules (based on behaviors like required) that run on every component

Why though?  This seems very expensive and might be difficult to maintain as more components (100+) are added.

If there are things that every component should have, maybe that should be handled at a different level?

> can we determine how a post will look on social media?

Like, grabbing their css?

> should we have the option to post to social media automatically when a page is published?

I think webhooks and microservices might be a saner place for this, maybe?

**Comment by yoshokatana** [comment]
I agree about using webhooks + microservices for this. Also, it looks like the `required` validation rule does check every component, so that's good.

**Comment by yoshokatana** [comment]
validation (error and warning) messages are done (in #447)

**Comment by nelsonpecora** [comment]
New (instant) validation is coming with Kiln v1.0, and the Url stuff is already handled in Amphora
