### ISSUE TITLE
publishing layouts

### ISSUE THREAD

**Issue by yoshokatana** [nymag/clay-kiln#320]
* ability to publish a layout (and thus publish all the components inside it)
* might depend on (or at least be a lot easier with) this amphora ticket: https://github.com/nymag/amphora/issues/202
* ability to schedule layout publishing? this would be a big help for things like special features and custom ads (though they might be page-specific)

**Comment by yoshokatana** [comment]
Until this is polished, UX-wise, I'm going to add a "publish layout now" link to the publish pane that'll do a `PUT` to `layout@published` with no data. With that Amphora ticket done, it'll re-publish the layout.

**Comment by TakenPilot** [comment]
Could you expand on this idea?  I forgot the conversation around these features you're describing, but it would be good to get some use-cases in here at least.

**Comment by yoshokatana** [comment]
I think the general case is somehow having a UI that will allow users of kiln to publish a layout (which really means cloning the latest version of the layout instance into `@published` and cloning any layout-specific components inside it to `@published` as well).

**Comment by yoshokatana** [comment]
This would allow us to completely remove layout-specific stuff from the bootstraps (everything except certain meta- components that aren't edited elsewhere)

**Comment by yoshokatana** [comment]
This is in
