### ISSUE TITLE
checkbox-group data structure

### ISSUE THREAD

**Issue by cruzanmo** [nymag/clay-kiln#337]
`checkbox-group` currently are deep objects and should be converted to arrays.

**Comment by TakenPilot** [comment]
Why, though?  We should get some use-cases and justification in here if we want to change an existing feature, and therefore break the current schemas that people are using.

**Comment by yoshokatana** [comment]
What Dane said

**Comment by yoshokatana** [comment]
Please reopen if you find a use case
