### ISSUE TITLE
hit ESC to close forms

### ISSUE THREAD

**Issue by yoshokatana** [nymag/clay-kiln#344]
Users should be able to close _any_ form they're in by hitting <kbd>esc</kbd>. This will have the exact same behavior in overlays, settings forms, inline forms, and `wysiwyg` fields with `enableKeyboardExtras` toggled.

**Comment by gloddy** [comment]
Yes, please.

**Comment by TakenPilot** [comment]
Isn't this really easy to do?

We can just do this, right?

Is there something blocking this?

**Comment by yoshokatana** [comment]
Nope, this should be super easy.
