### ISSUE TITLE
component-ref behavior comment support

### ISSUE THREAD

**Issue by yoshokatana** [nymag/clay-kiln#394]
For meta components (components that live in the `<head>`), we want to use html comments rather than putting `data-uri` in the `<meta>` tags (or `<title>`) directly. Doing the latter really messes with social media services and metadata parsers.

For this to work, the `component-ref` behavior should be able to find the specified selector in html comments.

```yaml
fn: component-ref
selector: '[data-uri*="/components/meta-image/"]'
```

Should match:

```html
<!-- data-uri="domain.com/path/components/name/instances/id" -->
```

As well as elements:

```html
<div data-uri="domain.com/path/components/name/instances/id"></div>
```

**Comment by cruzanmo** [comment]
Might need a closing comment tag as well. e.g. `<!-- end-data-uri="domain.com/path/components/name/instances/id" -->`

**Comment by yoshokatana** [comment]
The difference with comments is that they don't contain anything (especially the component's elements), we don't need a second comment.

**Comment by yoshokatana** [comment]
Is there any situation in which you'd need this functionality outside of the `<head>`?

**Comment by cruzanmo** [comment]
hmm, good question, seems maybe unlikely but possible. One example could be a textNode component like:
```
<!-- data-uri="{{ _ref or _self }}" -->
{{ string }}
<!-- data-uri="{{ _ref or _self }}" -->
```
