### ISSUE TITLE
component list breaks flexbox

### ISSUE THREAD

**Issue by ughitsaaron** [nymag/clay-kiln#457]
Kiln adds a wrapper div a component list's child elements. This breaks the component's style if flexbox is used to set the layout.

One possible solution is to grab the computed style of the parent of the list's elements. If the parent uses flexbox then set new wrapper to flexbox…

**Comment by yoshokatana** [comment]
Hmm, good point. What's a component whose children are flexed (so I can play around with this)?

**Comment by yoshokatana** [comment]
this works better now

**Comment by ughitsaaron** [comment]
lgtm. closing.
