### ISSUE TITLE
proposal: component deletion goes inside settings form

### ISSUE THREAD

**Issue by nelsonpecora** [nymag/clay-kiln#526]
@gloddy is into the idea that component deletion should perhaps go inside a component's settings form, which would remove a button from the selector. If we did this, we should also have some kind of keyboard shortcut that would (with a confirmation dialog) delete the currently selected component.

This would mean that _every_ component on the page would reliably have a settings form, even though some (most?) of them would simply contain the delete button.

**Comment by yoshokatana** [comment]
I'm not a huge fan of this idea because:

* having discoverable delete is a nice thing
* I can't figure out a keyboard shortcut that doesn't conflict with wysiwyg stuff
* the editing experience on mobile would be awful
