### ISSUE TITLE
proposal: kiln plugins

### ISSUE THREAD

**Issue by nelsonpecora** [nymag/clay-kiln#540]
Should work similarly to how behaviors, decorators, and validators work. Allows people's Clay installs to change the _editing experience itself_. Useful for things like spaces and word counts.

We could set this up similarly to how behaviors, decorators, and validators work. Basically an array of objects, with each containing some functions/hooks into kiln. Some ideas:

`init` - function that runs on page load, after kiln has run its controllers. can be used to add things to selectors, toolbar, etc.

`onSave` - function that gets called after any component saves

Alternatively, we could set this up with some kind of eventing system plugins could hook into, but there might be situations where we want to pause Kiln execution until a plugin has finished running.

**Comment by jonwinton** [comment]
`onFocus` for when highlighting a component?

**Comment by jonwinton** [comment]
Also, I think the `init` function needs to actually have multiple steps/hooks. One for hooking into the selectors, one for hooking into the toolbar, one for a controller to be added. I'm wondering if someone might make a plugin which has both a selector level interaction and a toolbar interaction.

**Comment by yoshokatana** [comment]
@jonwinton `focus` and `select` are different in kiln 😅 

`focus` is when an editable element is clicked, and it usually opens a form (and selects the component)

`select` is when any part of a component is clicked, and it shows the component selector

**Comment by jonwinton** [comment]
Hmmm more to think about: what/home do we expose as services available to plugins? Can every plugin access the progress or do we keep control outside of the hooks?

**Comment by jonwinton** [comment]
In working with the spaces component I'm finding services that need to be exposed for a plugin to take advantage of:

- creating a new component
- adding a component to a component list
- retrieving the data of a component from a uri
- being able to specify a component to select/focus on
- updating the selector of a component
- providing a different template for a selector (maybe?)
