### ISSUE TITLE
Word Count

### ISSUE THREAD

**Issue by jonwinton** [nymag/clay-kiln#542]
Assuming #540 is implemented, would it make sense to have a word count plugin that could tap into the save of an article, look inside it's child `clay-paragraph` components and generate a word count? Count could live in the toolbar?

**Comment by yoshokatana** [comment]
I don't think it should live in the toolbar (I really worry about crowding the toolbar and component selectors) but it should be able to hook into the component save events to update itself.

**Comment by jonwinton** [comment]
Agreed. I think this opens up a bigger question for plugins about if they can add content to a page that isn't part of a component wrapper.

Are we saying that components can manipulate what you see or are we limiting to adding content to only kiln specific places (like the toolbar or in a pane)?

**Comment by yoshokatana** [comment]
hmm, not sure.

**Comment by jonwinton** [comment]
Maybe we need to have a conversation about plugins since it seems like we're finding a couple use cases for them with a couple things? Probably a smattering of #540 and this? Maybe outline limitations/expectations?

**Comment by yoshokatana** [comment]
mhmm

**Comment by nelsonpecora** [comment]
this is done, as a plugin
