### ISSUE TITLE
proposal: display of select field with only one option

### ISSUE THREAD

**Issue by cruzanmo** [nymag/clay-kiln#604]
If there is only one option in a drop-down and it is the default value, then it need not display as a drop-down.

Currently:

![image](https://cloud.githubusercontent.com/assets/22883/18010478/a539d90c-6b7e-11e6-99f3-780698c8a81b.png)

Could render more like this:

![image](https://cloud.githubusercontent.com/assets/22883/18010555/ff3d5528-6b7e-11e6-83a0-587df3238b8e.png)

This situation is a symptom of `site-specific-select` when options lists are unique to each site and some sites only have one option. Perhaps this is an edge-case?

**Comment by nelsonpecora** [comment]
I think this is an edge case

**Comment by cruzanmo** [comment]
Yes, might be an edge case.

Also, if the select field renders significantly differently like this I could see it leading to confusion.
