### ISSUE TITLE
Masthead editor for masthead items overlaps masthead title editor

### ISSUE THREAD

**Issue by jessabean** [nymag/clay-kiln#635]
### Problem

Cannot use the text input to edit the masthead title. Clicking on the input triggers the editor for the inner masthead items.

This behavior occurs on the article, feature article, and one-column article templates while in edit mode.
### Steps to reproduce
- I'm using a copy of the `/press/` site locally
- Click on masthead title (e.g., "Contact Info"). The masthead title editor should appear.
- Click the input. The masthead editor for the masthead items will appear.

![clay-edit-bug](https://cloud.githubusercontent.com/assets/522911/18601119/14ed4f84-7c2f-11e6-8509-21af98588a11.gif)
### Potential fix

I think this has something to do with the z-index of the first `section.component-selector-wrapper` in the `section.masthead-items`. It has `z-index: 4`, and because of its padding, it overlaps the inline editor field for the masthead title, which has `z-index: 1`. You can kind of visualize it here:

<img width="398" alt="screen shot 2016-09-20 at 5 26 59 pm" src="https://cloud.githubusercontent.com/assets/522911/18689682/77978d8a-7f58-11e6-9667-e53ea1fd0bc2.png">

I _think_ this could be fixed by clearing the float on the masthead title when the editor is being displayed.

**Comment by nelsonpecora** [comment]
Hmm! I think you're right. I'm messing with the z-indices as part of the [new selectors](https://trello.com/c/34apsQdd/47-selectors), but I'm not sure if my work will actually fix this issue.

**Comment by nelsonpecora** [comment]
I think this was fixed by the latest selector update.
