### ISSUE TITLE
enforce Title Case in placeholder text?

### ISSUE THREAD

**Issue by nelsonpecora** [nymag/clay-kiln#638]
Should we do this? I think so.

**Comment by jonwinton** [comment]
What's the advantages of this? Just preference?

**Comment by gloddy** [comment]
We should choose either Title Case or Sentence Case for the appropriate places. Title Case is a more formal choice while Sentence Case is more casual (And easier to read for longer strings.)
A good real world example of the difference: iOS is Title Case while Android is Sentence Case.

**Comment by nelsonpecora** [comment]
It would keep the placeholders more consistent. Originally we didn't do anything, but we capitalized _some_ of the placeholders in components and not others. For the new placeholders, I think making it consistent would keep the UI spiffy.

**Comment by gloddy** [comment]
@nelsonpecora Agreed. Worth it for a consistent UX.
