### ISSUE TITLE
base component value not populating for radio behavior

### ISSUE THREAD

**Issue by cruzanmo** [nymag/clay-kiln#668]
e.g.

`site.com/path/components/some-component` returns `{a: 'hello'}`

`site.com/path/components/some-component/schema` returns

```
a: {
  _has: [
    {
      fn: "radio",
      options: [
        "hello",
        "goodbye"
      ]
    }
  ]
}
```

When the component is added to a componentList, the value of the radio is empty. e.g. `site.com/path/components/some-component/instances/some-new-one` returns `{a: ''}`

**Comment by nelsonpecora** [comment]
Let's make sure we test agains this before releasing v1.0

**Comment by nelsonpecora** [comment]
@cruzanmo do you have an example component I can test this against?

**Comment by nelsonpecora** [comment]
I can't repro this
