### ISSUE TITLE
Hitting `esc` to close a `_display: overlay` modal can prevent the modal from opening up again

### ISSUE THREAD

**Issue by byronhulcher** [nymag/clay-kiln#676]
I have an element with a placeholder and `_display: overlay` and if I click the placeholder, hit `esc` before changing any data, then I am unable to click the placeholder again to open up the overlay until I edit another field's data.

In my test the overlay only contained a single field with `fn: radio`, not sure if that is relevant.

Steps to reproduce:
1) I click into the placeholder
2) The overlay appears
3) Without modifying any data, I hit `esc`
4) I click the placeholder again

Expected:
The overlay appears again

Actual:
The overlay does not appear.  

Notes:
If I modify the data of the element, then hit `esc`, I am allowed to open the overlay again.

If I click `save` in the overlay instead of hitting the `esc` key, without modifying any data, I am able to open the overlay again.

Clicking into a different inline field or clicking into the placeholder of a different field with `display: overlay` allows the original field to be clicked again to open the original field overlay.

**Comment by nelsonpecora** [comment]
Let's make sure we test agains this before releasing v1.0

**Comment by nelsonpecora** [comment]
I added the ESC behavior again, and it's a bit simpler than in old kiln. https://github.com/nymag/clay-kiln/issues/800

@byronhulcher what component can I test this against?

**Comment by nelsonpecora** [comment]
confirmed this works in new kiln (tested on article » custom date)
