### ISSUE TITLE
Bad edit view

### ISSUE THREAD

**Issue by alliesahn** [nymag/clay-kiln#747]
`Label` field and `Hide Label` checkbox are grouped in this, but the edit view is bad :(
Would be better if the text box didn't take up the whole width and the checkbox and label were placed directly next to it. Also would be nicer if the checkbox label was smaller (in the event where a checkbox is part of a group)

![screen shot 2017-01-26 at 4 48 08 pm](https://cloud.githubusercontent.com/assets/8642737/22351873/da03161c-e3e7-11e6-9fc9-27bf27563366.png)

**Comment by nelsonpecora** [comment]
Text inputs (text, textarea, and wysiwyg) need to span the whole width, since they interact with other things in that space already (magic button, lock, mediaplay picker, etc). In Kiln v1.0, behaviors will be added to different slots in the field (before, main, after) in a more consistent fashion.
