### ISSUE TITLE
'View' link in bottom bar post-publish is not clickable when a page is first published

### ISSUE THREAD

**Issue by byronhulcher** [nymag/clay-kiln#767]
Repro:
1. Create a new article
2. Click `Draft` button
3. Click `Publish Now`
4. After publish, bar appears with 'View' link which has an href links to the articles published URL

Expected:
5. I can left-click the 'View' link and it will open in a new tab

Actual:
5. Left-clicking the 'View' link does not open the published page, in a new tab or otherwise. It is possible to right-click the 'View' link and select 'Open in New Tab' or 'Open in New Window' and it will open the correct published page.

Notes:
This only occurs the FIRST time an article is published.  If one refreshes the page after publishing, then repeats steps 2-4, they are able to left-click the 'View' link to open the published article at its proper URL

Demo'd IRL for @nelsonpecora on my local machine

**Comment by nelsonpecora** [comment]
Let's make sure we test agains this before releasing v1.0

**Comment by nelsonpecora** [comment]
fixed in new kiln
