### ISSUE TITLE
Placeholder for component list does not dissappear after adding a component

### ISSUE THREAD

**Issue by byronhulcher** [nymag/clay-kiln#773]
To repro:
1) Load a page with a component (such as article) that has an component list with a placeholder (such as `content` for article)
2) Remove all elements in `content`
3) **Reload the page after making sure all components are removed and the component list is empty**
4) You will see the placeholder
5) Add a component

Expected:
6) The placeholder dissappears

Actual:
6) The placeholder is still there, beneath the newly added component

Notes:
Just to re-iterate, this only seems to occur when the page is first loaded and the placeholder is visible.  If you load the page with components in the component list, remove them (thus making the placeholder appear), and then re-add a component, then the placeholder will disappear as expected.

**Comment by nelsonpecora** [comment]
Let's make sure we test agains this before releasing v1.0

**Comment by nelsonpecora** [comment]
fixed in new kiln. yay reactive rendering
