### ISSUE TITLE
Trailing </a> tag after URL

### ISSUE THREAD

**Issue by alliesahn** [nymag/clay-kiln#774]
Copying and pasting paragraphs with individual mediaplay or video links from google doc leaves a trailing `</a>` tag after the URL (e.g., copying and pasting [this doc](https://docs.google.com/document/d/1KbIJJxBoE9fz2bjcvsXvDfXxM3aiMZs7DK2leFZ7Nhw/edit) into a paragraph component).
[This PR](https://github.com/nymag/sites/pull/2739) has a temporary fix for that bug, but should be revisited once new kiln is out

**Comment by nelsonpecora** [comment]
looks like this is fixed in new kiln
