### ISSUE TITLE
Form checkbox group bug

### ISSUE THREAD

**Issue by jonwinton** [nymag/clay-kiln#808]
See attached gif.

- Can click outside of a checkbox and the first input will be selected
- Clicking any checkbox looks also interacts with the first checkbox, though it's selected state is not affected.

https://dl.dropboxusercontent.com/s/yow9zebvlc020d3/FFD7C45E-CAB4-4C6E-9D7B-3094C181B5D8-9068-000032D7533019C0.gif?dl=0

**Comment by nelsonpecora** [comment]
I think this issue has something to do with labels

**Comment by nelsonpecora** [comment]
fixed in commit 81db000
