### ISSUE TITLE
Remove `display: inherit` from `.component-list-inner`

### ISSUE THREAD

**Issue by byronhulcher** [nymag/clay-kiln#839]
Since `.component-list-inner` is now added to an editable element, rather than created as an intermediate child of an element, we should remove the `display: inherit` rule as it can seriously mess up the CSS of a component in edit mode:

![image](https://cloud.githubusercontent.com/assets/2479295/25457268/b62ef0be-2aa3-11e7-8367-22f8225a3e4a.png)

**Comment by nelsonpecora** [comment]
fixed in commit 390bf6d
