### ISSUE TITLE
Recirc Area Closes Unexpectedly

### ISSUE THREAD

**Issue by pfeytser** [nymag/clay-kiln#840]
When clicking from field to field in recirc area, specifically between Facebook and Twitter headlines, the recirc form closes.

![screen shot 2017-05-02 at 12 45 13 pm](https://cloud.githubusercontent.com/assets/10674066/25669980/4ffb9a4e-2ff9-11e7-8d6f-15f18ad56764.png)

**Comment by nelsonpecora** [comment]
I think this has been fixed by the refactoring I did for kiln beta 1, but let's test and verify once that's on a server.

**Comment by nelsonpecora** [comment]
Yep, I cannot repro this in any kiln beta
