### ISSUE TITLE
Disappearing Bottom Paragraph When Splitting Paragraphs

### ISSUE THREAD

**Issue by pfeytser** [nymag/clay-kiln#842]
Clicking backspace at beginning of paragraph makes the focused paragraph disappear. When you click into the paragraph above it was supposed to be combined with, it correctly re-appears.

<a href="https://dl.dropboxusercontent.com/s/vygo91xqvehsyir/A12A8FAB-7FB8-488B-99E3-BBA1394FFA7E-15572-000022BC1C3E2E52.gif?dl=0">See GIF</a>

**Comment by nelsonpecora** [comment]
fixed in commit 680fbd4

it wasn't grabbing the previous paragraph's element from the dom (which it needed to do, since it's being re-rendered)

**Comment by pfeytser** [comment]
@nelsonpecora I can still repro this bug.

**Comment by nelsonpecora** [comment]
I still can't repro this 😞
