### ISSUE TITLE
Selector Disappears When Highlighting Text Leftward Beyond Selector

### ISSUE THREAD

**Issue by pfeytser** [nymag/clay-kiln#843]
When highlighting text, dragging the mouse far to the left beyond the component selector causes the selector to disappear. Text is editable. 

<a href="https://dl.dropboxusercontent.com/s/mogqkymeo4j8ld8/F00BA22C-DF38-4485-885A-3A2DD42834A8-15572-0000233672FAD3B3.gif?dl=0">See it in action here</a>

**Comment by nelsonpecora** [comment]
fixed in commit c76ebe5
