### ISSUE TITLE
Publish Progress Bar

### ISSUE THREAD

**Issue by jonwinton** [nymag/clay-kiln#847]
When publishing there's no progress bar. I tried to capture it in this gif but it _may_ have been too fast. When I tested before there was a slow response from the server so it took awhile to publish and it was very apparent.

https://dl.dropboxusercontent.com/s/t3w49m5a5vz85zp/28EB97A9-912C-4A7D-B9F6-41B9F6FA72FF-524-00001EC09B1767D5.gif?dl=0

Just want to double check it's in there

**Comment by nelsonpecora** [comment]
fixed in commit 1ffa2bc
